meta_product_name: "Food Next Door"
meta_title: "Food Next Door - Order a home cooked meal from your neighbors"
meta_description: "Relevant description"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
